package com.bangkit.rentalbiz.dummy

data class Product(
    val name: String,
    val image: String,
    val price: String,
    val location: String,
    val rating: Double,
    val description:String,
    val requirenment: String,
)

object DummyProductData {
    val productList = listOf<Product>(
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",

        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Cannon 5D Mark IV",
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            "200000",
            "Bandung",
            4.5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),

        )
}