package com.bangkit.rentalbiz.dummy

import com.bangkit.rentalbiz.data.remote.response.Product

object DummyProductData {
    val productList = listOf<Product>(
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            1,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            2,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            3,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            4,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            5,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            6,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            7,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            8,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            9,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),
        Product(
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
            1,
            "Bandung",
            "0",
            "kamera",
            10,
            1,
            "Cannon 5D Mark IV",
            200000,
            "",
            10,
            "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
            10,
            "Lorem ipsum dolor sit amet consectetur. Montes dui diam eu aliquet. Nam pellentesque consequat quis vulputate tempus urna lorem tortor orci. Volutpat turpis pellentesque tincidunt porttitor sagittis nulla tristique ut risus.",
        ),


        )
}